### ISSUE TITLE
Regularization in blocking

### ISSUE THREAD

**Issue by mschauer** [mmider/FitzHughNagumo.jl#15]
In inference_with_blockscript, line 55 gives the same regularisation as line 68, should this be coupled automatically?

**Comment by mmider** [comment]
They are set to the same level in this script, but they are regularising slightly different things. The regularisation in line 55 is regularising partially observed points. The regularisation in line 67 (I guess this is the one you referred to, i.e. `10^(-10)` in `blockingParams = (collect(1:length(obs)-2)[1:2:end], 10^(-10), SimpleChangePt(100))` ) is regularising the artificial, exactly observed knot in the blocking scheme. Initially they had to be kept separately, because prior to introducing feature of switching between two ODE solvers (between solvers for `M`, `mu` and `L` and solvers for `H`, `Hnu` and `c`) exact observation of the knot was more difficult to handle numerically. Consequently, when only solvers for  `H`, `Hnu` and `c` are used throughout, then the regularisation parameter in line 67 needs to be smaller than the one in line 55. Currently, because solvers for `M`, `mu` and `L` are behaving better, the two can be set to equally low values ... at least in the example I tested it on. However I don't know if it won't break in other examples, so I think it might be better to keep those separately. Maybe some intelligent default setting which sets them to the same level might be a good compromise.
